apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sljk-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #cert-manager.io/issuer: "letsencrypt-staging"

spec:
  tls:
    - hosts:
        - davidsljukic.xyz
      secretName: quickstart-example-tls
  rules:
    - host: davidsljukic.xyz
      http:
        paths:
          - path: /
            backend:
              serviceName: portfolio-service
              servicePort: 80
